name: task_sharing
description: Gestión de tareas
publish_to: "none"
version: 1.4.2

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  dio: ^5.3.3
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  # firebase_messaging: ^14.7.4
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_riverpod: ^2.4.5
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  intl: ^0.18.1
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  page_view_dot_indicator: ^2.3.0
  permission_handler: ^11.0.1
  riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  talker_dio_logger: ^2.3.1
  text_scroll: ^0.2.0
  url_launcher: ^6.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  build_runner: ^2.4.6
  change_app_package_name: ^1.1.0
  custom_lint: ^0.5.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/data/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/list.png"
  min_sdk_android: 21 # android min sdk min:16, default 21



flutter_native_splash:
  # color: "#ffffff"
  # # background_image: assets/icon/icon_background.png
  # image: assets/icons/list.png
  # # color_dark: "#59dbbc"
  # # image_dark: assets/icon/icon2.png

  # # android_12:
    
  # #   image_dark: assets/icon/icon2.png
  # #   color_dark: "#CFF1F1"
  # #   icon_background_color_dark: "#CFF1F1"
  # android: true
  # ios: true
  # web: false
  color: "#ffffff"
  color_dark: "#ffffff"
  image: assets/icons/list_splash.png
  image_dark: assets/icons/list_splash.png

  android: true
  ios: true
  web: false

  android_gravity: fill
  android_12:
    color: "#ffffff"
    color_dark: "#ffffff"
    icon_background_color_dark: "#ffffff"
    image: assets/icons/list_splash.png